### ISSUE TITLE
[FR] Add support for Typst

### ISSUE THREAD

**Issue by Ciflire** [ltex-plus/vscode-ltex-plus#74]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Using actual real-world examples that explain why you and many other users would benefit from the feature increases the request's chances of being implemented.
Typst is a pretty new markup language, it does already work pretty well but could it could be better. Also the filetype needs to be added to `ltex.enable` manually in the settings.
The main issues I have noted are syntactic sugar, we use `-` to note list items that are considered as dashes, also could be related to bad setup, but it doesn't reanalyze the file on edit or save (tried both) as set in the settings

**Describe the solution you'd like**
I'd like that language to be better supported, would also be cool to extend the `enabled` option to add smth like a wildcard of language modes the user want the extension to check, easier than editing the `config.json`

**Describe alternatives you've considered**
At the moment there are no grammar checker, especially not in my language for typst your project is, to my knowledge, the closest to support typst

**Comment by spitzerd** [comment]
I added a basic support for Typst. You can test the nightly release already.

Regarding your wish about a wildcard of language modes: I will check if and how this can be implemented. 

Pull requests are welcome, of course.

**Comment by Ciflire** [comment]
i cannot test that right now as i don't use vscode on my computer, i'll tell you tomorrow
tho i've tried to test it with my current helix setup and it doesn't work at all, if you have any advice to give for this

**Comment by Ciflire** [comment]
sorry cannot try until release on this computer...

**Comment by spitzerd** [comment]
You cannot install the nightly release? What is the issue you are facing?

https://github.com/ltex-plus/vscode-ltex-plus/releases/tag/nightly

**Comment by Ciflire** [comment]
I downloaded it, but I'm on a restricted computer that doesn't want to install via the build output, only via the extension manager inside of VSCode, and it doesn't seem to be available yet

**Comment by Esteban795** [comment]
Hello,
First, thanks for your work on this extension, it works very well with Latex.

I would like to report two bugs I have found in the nightly build so far for Typst (which is why I'm commenting here instead of a new issue) : 
- Words that are inside quotes in math mode seem to not be detected anymore (it was in the official release build). Example : `$ "exersice" 3 + 4$` doesn't report 'exersice' (I'm french, so it's written 'exercice', and the extension is indeed set to be check for french grammar). Official release does report it as wrong.
- Not really a bug, but rather a clash between conventions in Typst formatters. When calling a function like `#definition(title : "Définition de topologie")`, it reports an error saying a space is necessary, It is only corrected if I instead write `#definition( title : "Définition de topologie")`. I used both typststyle and typstfmt as formatter to check if any of the two formatted with the space after the parenthesis, and both agree on no space after parenthesis.

Thank you for your time !

Edit : 
The second bug is also in the official release, not only the nightly build.

**Comment by spitzerd** [comment]
@Ciflire 
Alright, then you have to wait for the next release.

@Esteban795 
I excluded the text from math mode by purpose. But your example shows that it can be useful to check the content of the math mode as well. I will adapt the coding accordingly. Regarding your second point, I will provide a fix as well.

**Comment by spitzerd** [comment]
@Esteban795 Your two points should be solved by the next nightly release. In addition, I added support for the escaping character, which is the backslash symbol  in Typst.

**Comment by Esteban795** [comment]
Thank you very much !

**Comment by cgahr** [comment]
>
> * Words that are inside quotes in math mode seem to not be detected anymore (it was in the official release build). Example : `$ "exersice" 3 + 4$` doesn't report 'exersice' (I'm french, so it's written 'exercice', and the extension is indeed set to be check for french grammar). Official release does report it as wrong.
>
In my opinion, there should be no spell checking in equations. I think there will just be to many false positives:
```
$ macron(lambda) $
$ a_(i parallel)$
```
Both equations would for example have spelling mistakes in them. Even if only `"` delimited strings are checked, I think there would be to many false positives..

**Comment by Ciflire** [comment]
@cgahr @Esteban795 specified "words that **are inside quotes** in math mode"
I do agree with you tho, math tokens should not be checked

**Comment by cgahr** [comment]
I missed that, my bad.

**Comment by spitzerd** [comment]
Strings in math mode are checked now. Please test again.

**Comment by Ciflire** [comment]
this was improved
i don't know how to develop all this, but i could provide like test cases of what (to me) should be tested and what should'n does that interest you? if yes, what format would be best for you?

**Comment by spitzerd** [comment]
Yes, test cases would be fine. I am especially interested in cases of where a spelling mistake is displayed but it is correct (false positives).

A txt file is totally fine.

**Comment by ainar** [comment]
Hello, is there a way to configure Typst functions like [`ltex.latex.commands`](https://ltex-plus.github.io/ltex-plus/settings.html#ltexlatexcommands)?

**Comment by spitzerd** [comment]
@ainar 
No it's not possible so far. If there is a need to have it for Typst as well, feel free to create a feature request.

**Comment by AdiWeit** [comment]
I have a few false positives I'd like to share: 
In `#set cite(style: "apa")` or `#bibliography("works.yml", style: "apa")` it says apa is misspelled (I guess this is not dependent on the style)
In `#show link: underline` it says underline is misspelled (because I write and spellcheck in German)
In `#show link: set text(rgb(0, 0, 255))` it says a '(' is missing for some reason
In #show cite: set text(weight: "bold") it says bold is misspelled (because I write and spellcheck in German)
Also, it does not recognize sentence beginnings after a heading: 
```typst
= Vorgehensweise
Ein Satz für euch. 
```
When having a citation at the end of the sentence like `#cite(<reasoning-c-sharp>).` it says there should be no space before the period
I guess the workaround (other than ignoring the messages) for now is to disable these error types all together.

**Comment by spitzerd** [comment]
@AdiWeit I created issue https://github.com/ltex-plus/ltex-ls-plus/issues/72  for you, because this one is closed.
